#
# Copyright (C) 2023 Geonames Indexer.
#
# Geonames Indexer is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

#
# OpenSearch configuration.
#
opensearch.config.hosts = [
    { host = "localhost", port = 9200 }
]
